services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    env_file:
      - .env.prod

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
